services:
  db:
    image: mysql:8.0
    restart: no
    container_name: werwolf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "42069:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./werwolf.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: