spring.application.name=backend

# db config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:42069/game_werwolf?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# jpa config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# grpc server
grpc.server.port=9090
# ping every 60 sec; close the connection if no ACK arrives within 20 s
grpc.server.keep-alive-time=60s
grpc.server.keep-alive-timeout=20s
# Accept client initiated pings ; no faster than every 30 s.
grpc.server.permit-keep-alive-without-calls=true
grpc.server.permit-keep-alive-time=30s

# jwt
jwt.secret=${JWT_SECRET:werewolf-secret-key-must-be-at-least-32-characters-long}